# dbt_project.yml - VERSIÓN CORREGIDA
name: elt_pipeline_stocks
version: "1.0.0"
config-version: 2

profile: elt_pipeline_stocks

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]

models:
  elt_pipeline_stocks:
    +materialized: table
