# profiles.yml
elt_pipeline_stocks:
  target: dev
  outputs:
    dev:
      type: postgres
      host: stocks_dwh_postgres
      user: postgres
      password: postgres
      port: 5432
      dbname: stocks_dwh
      schema: public
      threads: 4
